In [1]:
import numpy as np

In [2]:
a=np.array([2.1,3,4.2,5,7,8,3,1,3,0])
b=np.array([22,32,41,35,7,8,3,1,13,0])
print(a)
print(b)

[2.1 3.  4.2 5.  7.  8.  3.  1.  3.  0. ]
[22 32 41 35  7  8  3  1 13  0]


In [3]:
type(a)

numpy.ndarray

In [4]:
b.dtype

dtype('int32')

In [5]:
a.dtype

dtype('float64')

In [6]:
#generate a sequence of equally spaced values between start and end(linspace)

#array_name=n.linspace(start,end,no. of elements)
a=np.linspace(2,20,10)
a

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [7]:
#generate random numbers between 0 and 1
a=np.random.random(10)
a

array([0.05506308, 0.01539685, 0.34565828, 0.79011199, 0.89006231,
       0.48651996, 0.54588734, 0.04972685, 0.45950952, 0.47291797])

In [8]:
#generate random integer between start(inclusive) and end(exclusive)
#array_name=np.random.randint(start,end,noe)

arr2=np.random.randint(1,10,10)
arr2

array([6, 4, 2, 6, 9, 1, 5, 7, 3, 9])

In [9]:
#generate a 2D array of random numbers
#array_name=np.random.randit(start,end,(row,column))
arr3=np.random.randint(1,10,(3,3))
arr3

array([[8, 7, 6],
       [3, 2, 2],
       [4, 8, 1]])

In [10]:
arr3.itemsize #size of each element of the array

4

In [11]:
arr3.shape # no of rows and column

(3, 3)

In [12]:
arr3.size #size of elements in array

9

In [13]:
arr3.nbytes #total size of the array in bytes

36

In [14]:
arr3.ndim #dimension of the array

2

In [15]:
b=np.random.randint(1,10,(4,4))
b

array([[7, 5, 9, 7],
       [1, 4, 4, 8],
       [5, 4, 7, 2],
       [8, 4, 8, 2]])

In [16]:
b.shape


(4, 4)

In [17]:
b.size

16

In [18]:
b.nbytes

64

In [19]:
b.ndim

2

In [20]:
b.itemsize

4

In [21]:
n= np.arange(10) #generate sequence (start,end ,step)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
n.dtype 

dtype('int32')

In [23]:
n.astype('float') #convert to other datatype

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
#add elemets to the array
arr=np.array([2,10,7,8])
np.append(arr,6)
#extend

array([ 2, 10,  7,  8,  6])

In [25]:
arr3

array([[8, 7, 6],
       [3, 2, 2],
       [4, 8, 1]])

In [26]:
np.append(arr3,10) #use append add 1 elemets

array([ 8,  7,  6,  3,  2,  2,  4,  8,  1, 10])

In [27]:
np.append(arr3,(1,23,5))  #use tuple to add more elemets

array([ 8,  7,  6,  3,  2,  2,  4,  8,  1,  1, 23,  5])

In [28]:
#np.insert(array_name,osition,elements)
np.insert(arr,2,8)

array([ 2, 10,  8,  7,  8])

In [29]:
arr3

array([[8, 7, 6],
       [3, 2, 2],
       [4, 8, 1]])

In [30]:
np.insert(arr3,2,8)

array([8, 7, 8, 6, 3, 2, 2, 4, 8, 1])

In [31]:
#np.insert(array.position,value,axix=0/1)
#axis 0:row
#axis 1:column
np.insert(arr3,2,3,axis=0)

array([[8, 7, 6],
       [3, 2, 2],
       [3, 3, 3],
       [4, 8, 1]])

In [32]:
np.array([[1,2,3,4],[3,4,5,6],[2,4,5,6,],[4,6,7,7]])

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [2, 4, 5, 6],
       [4, 6, 7, 7]])

In [33]:
np.insert(arr3,2,3,axis=1)

array([[8, 7, 3, 6],
       [3, 2, 3, 2],
       [4, 8, 3, 1]])

In [34]:
np.insert(arr3,2,[4,3,2],axis=1) #to add a column

array([[8, 7, 4, 6],
       [3, 2, 3, 2],
       [4, 8, 2, 1]])

In [35]:
#delete element from an array
#np.delete(array_name,position)
s=np.random.randint(1,10,(2,3))
arr3

array([[8, 7, 6],
       [3, 2, 2],
       [4, 8, 1]])

In [36]:
s

array([[3, 6, 8],
       [7, 7, 1]])

In [37]:
s1=np.delete(arr3,4) #delete element with position
s1

array([8, 7, 6, 3, 2, 4, 8, 1])

In [38]:
s2=np.delete(arr3,2,axis=1) #delete row/column with position
s2

array([[8, 7],
       [3, 2],
       [4, 8]])

In [39]:
np.delete(arr3,(1,0),axis=1)

array([[6],
       [2],
       [1]])

In [40]:
a=np.array([1,2,3,4])
b=np.copy(a)


In [41]:
b

array([1, 2, 3, 4])

In [42]:
#Ascending and descending
c=np.array([3,1,4,0])
sort_a=np.sort(c)
sort_a

array([0, 1, 3, 4])

In [43]:
np.sort(c)[::-1]

array([4, 3, 1, 0])

In [44]:
c

array([3, 1, 4, 0])

In [45]:
c.sort() #sort() method
c

array([0, 1, 3, 4])

In [46]:
c

array([0, 1, 3, 4])

In [47]:
a1=np.random.randint(1,10,(3,3))
a1

array([[8, 5, 4],
       [5, 9, 7],
       [8, 5, 4]])

In [48]:
a2=np.random.randint(1,10,(3,3))
a2

array([[1, 9, 7],
       [4, 3, 4],
       [9, 4, 1]])

In [49]:
a3=np.random.randint(1,10,(3,3))
a3

array([[7, 8, 9],
       [1, 4, 6],
       [8, 4, 4]])

In [50]:
np.vstack([a1,a2,a3]) #vertical stacking

array([[8, 5, 4],
       [5, 9, 7],
       [8, 5, 4],
       [1, 9, 7],
       [4, 3, 4],
       [9, 4, 1],
       [7, 8, 9],
       [1, 4, 6],
       [8, 4, 4]])

In [51]:
np.hstack([a1,a2,a3])

array([[8, 5, 4, 1, 9, 7, 7, 8, 9],
       [5, 9, 7, 4, 3, 4, 1, 4, 6],
       [8, 5, 4, 9, 4, 1, 8, 4, 4]])

In [52]:
np.concatenate([a1,a2,a3],axis=0) #same as vstack

array([[8, 5, 4],
       [5, 9, 7],
       [8, 5, 4],
       [1, 9, 7],
       [4, 3, 4],
       [9, 4, 1],
       [7, 8, 9],
       [1, 4, 6],
       [8, 4, 4]])

In [53]:
np.concatenate([a1,a2,a3],axis=1) #same as hstack

array([[8, 5, 4, 1, 9, 7, 7, 8, 9],
       [5, 9, 7, 4, 3, 4, 1, 4, 6],
       [8, 5, 4, 9, 4, 1, 8, 4, 4]])

In [54]:
a1.ravel() #to convert to 1d array

array([8, 5, 4, 5, 9, 7, 8, 5, 4])

In [55]:
#Numpy slicing

In [56]:
#arr[row,col]
#arr[start:stop:step,start:step]
a1

array([[8, 5, 4],
       [5, 9, 7],
       [8, 5, 4]])

In [57]:
a1[0,1]

5

In [58]:
a1[[0,1,2],[1,2,2]]

array([5, 7, 4])

In [59]:
a4=np.random.randint(1,10,(4,5))
a4

array([[1, 5, 1, 8, 8],
       [7, 4, 8, 5, 9],
       [1, 1, 9, 9, 7],
       [4, 1, 5, 3, 2]])

In [60]:
a4[0::2,:]

array([[1, 5, 1, 8, 8],
       [1, 1, 9, 9, 7]])

In [61]:
a4[1::2,0::2]

array([[7, 8, 9],
       [4, 5, 2]])

In [62]:
arr3=np.zeros((8,8))
arr3
arr3[1::2,1::2]=1
arr3[0::2,0::2]=1


arr3


array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [63]:
a1


array([[8, 5, 4],
       [5, 9, 7],
       [8, 5, 4]])

In [64]:
a2

array([[1, 9, 7],
       [4, 3, 4],
       [9, 4, 1]])

In [65]:
a1*a2 #normal multiplication

array([[ 8, 45, 28],
       [20, 27, 28],
       [72, 20,  4]])

In [66]:
np.matmul(a1,a2) #matrix multiplication

array([[ 64, 103,  80],
       [104, 100,  78],
       [ 64, 103,  80]])

In [67]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [68]:
b=np.full((3,2),5)
b

array([[5, 5],
       [5, 5],
       [5, 5]])

In [69]:
np.matmul(a,b)


array([[15., 15.],
       [15., 15.]])

In [107]:
c=np.full((3,2),5)
c

array([[5, 5],
       [5, 5],
       [5, 5]])

In [109]:
np.shape(c)

(3, 2)

In [71]:
np.max(a1)

9

In [72]:
np.min(a1)

4

In [73]:
a1

array([[8, 5, 4],
       [5, 9, 7],
       [8, 5, 4]])

In [74]:
np.max(a1,axis=0) # down to  column

array([8, 9, 7])

In [75]:
np.min(a1,axis=0) #column

array([5, 5, 4])

In [76]:
np.max(a1,axis=1) #column

array([8, 9, 8])

In [77]:
np.min(a1,axis=1) #column

array([4, 5, 4])

In [78]:
#LOADING TEXT FILES

In [79]:
import os
os.getcwd() #get current working directory

'C:\\Users\\HP'

In [80]:
data=np.genfromtxt(r'C:\\Users\\HP\abc.txt',delimiter=',')
data

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [4., 5., 6., 7., 7., 8., 3., 5., 3.],
       [2., 3., 5., 6., 4., 3., 2., 1., 4.],
       [2., 4., 5., 3., 5., 3., 5., 3., 5.]])

In [81]:
data1=np.genfromtxt('abc.txt',delimiter=',')
data1

array([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
       [4., 5., 6., 7., 7., 8., 3., 5., 3.],
       [2., 3., 5., 6., 4., 3., 2., 1., 4.],
       [2., 4., 5., 3., 5., 3., 5., 3., 5.]])

In [82]:
data.dtype

dtype('float64')

## Boolean masking

In [83]:
data1>6

array([[False, False, False, False, False, False,  True,  True,  True],
       [False, False, False,  True,  True,  True, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [84]:
data1>=6

array([[False, False, False, False, False,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True, False, False, False],
       [False, False, False,  True, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [85]:
data1==6

array([[False, False, False, False, False,  True, False, False, False],
       [False, False,  True, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [86]:
data1!=6

array([[ True,  True,  True,  True,  True, False,  True,  True,  True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [87]:
np.all(data1>5,axis=1)

array([False, False, False, False])

In [88]:
np.any(data1>5,axis=1)

array([ True,  True,  True, False])

In [89]:
np.all(data1>5,axis=0)

array([False, False, False, False, False, False, False, False, False])

In [90]:
# condition selection
data1[data1>5]


array([6., 7., 8., 9., 6., 7., 7., 8., 6.])

In [91]:
data1[((data1>5) & (data1<8))]

array([6., 7., 6., 7., 7., 6.])

In [92]:
# np.split(array_name, number_of_splits,axis)
ab=np.array([[1,2,3],[2,3,4],[4,5,6]])
np.split(ab,3,axis=0) #splits must be equal

[array([[1, 2, 3]]), array([[2, 3, 4]]), array([[4, 5, 6]])]

In [93]:
np.split(ab,3,axis=1)

[array([[1],
        [2],
        [4]]),
 array([[2],
        [3],
        [5]]),
 array([[3],
        [4],
        [6]])]

In [94]:
# np.split(arr,[a,b],axis=0/1) --- arr[:a], arr[a:b], arr[b:]
abc=np.array([[1,2,3],[3,4,5],[6,7,8]])
abc

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
np.split(abc,[2,6],axis=0)

[array([[1, 2, 3],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([], shape=(0, 3), dtype=int32)]

## comparing array

In [96]:
a=np.array([1,2,3])
b=np.array([2,4,5])

In [97]:
#element wise comparison
np.equal(a,b)

array([False, False, False])

In [98]:
#comparing full array
np.array_equal(a,b)

False

In [102]:
import warnings
warnings.filterwarnings("ignore")

In [140]:
#Array Broadcasting
a1=np.array([[1,2,3],[2,3,4],[4,5,6]])
b1=np.array([[2,4,5]])

In [141]:
a1

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [142]:
b1

array([[2, 4, 5]])

In [145]:
# np.sum([a1,b1])

In [135]:
np.shape(a1), np.shape(b1)

((3, 3), (1, 3))

In [144]:
a1+b1

array([[ 3,  6,  8],
       [ 4,  7,  9],
       [ 6,  9, 11]])